### ISSUE TITLE
Zou het status object uit de yaml gehaald kunnen worden?

### ISSUE THREAD

**Issue by NickHardy** [VNG-Realisatie/gemma-zaken#1526]
# Bug

In de openapi.yaml staat een extra status object. Deze conflicteerd met het Status object met een hoofdletter.
Zou deze uit de yaml van de gereleaste versie verwijderd kunnen worden?

`status:
type: object
allOf:
- $ref: '#/components/schemas/ZaakObject'
`

**Comment by sergei-maertens** [comment]
Open API is [case sensitive](https://swagger.io/specification/#format), dus dit zou valide moeten zijn toch?

**Comment by NickHardy** [comment]
@sergei-maertens 
Ik denk dat de yaml wel valide is, maar blijkbaar zijn niet alle code generatoren case sensitive.
Ik had begrepen dat die status alleen voor testen wordt gebruikt, vandaar mijn vraag.
Ik zal ook issues aanmaken bij de diverse code generatoren die ik gebruik. Daar zou het opgelost moeten worden.

**Comment by sergei-maertens** [comment]
Ik heb even gekeken - ik ben vrijwel zeker dat het probleem inderdaad bij de code generators zit.

> Ik had begrepen dat die status alleen voor testen wordt gebruikt, vandaar mijn vraag.

Kan je dit wat verduidelijken?

We hebben namelijk de `Status` resource, wat de zaakstatussen vorm geeft, en daarnaast is er het attribuut `status` op een `Fout` die de HTTP status code bevat en conform een RFC & de landelijke API strategie opgebouwd is, dus beide kunnen er niet uitgehaald worden :-)

**Comment by sergei-maertens** [comment]
Ik heb net even kort overlegd, `status` verwijst inderdaad wel naar een zaakstatus, en omdat deze via de API's ontsloten wordt is er eigenlijk geen behoefte om die via `objectIdentificatie` te kunnen ontsluiten (dit is een oplossing om met de grenzen van het API landschap om te kunnen gaan). In principe zou deze er dus uit kunnen, al is dat geen change die we nu zomaar kunnen doorvoeren aangezien het breaking is.

Ik denk dat dit een kandidaat wordt voor 2.0 :thinking:

**Comment by NickHardy** [comment]
2.0 is prima
Tot die tijd kan ik er wel omheen werken.

**Comment by HenriKorver** [comment]
> In principe zou deze er dus uit kunnen, al is dat geen change die we nu zomaar kunnen doorvoeren aangezien het breaking is.

Het schema-element `status` is net zoals alle andere instanties van ZaakObject (adres, besluit, buurt, etc.) wel gedeclareerd maar wordt verder helemaal niet gebruikt in de OAS-specificatie. In mijn Swagger editor krijg ik hiervoor warnings. Volgens mij kun je al deze onterechte declaraties uit de OAS verwijderen zonder dat dat invloed heeft op de API.

**Comment by sergei-maertens** [comment]
@HenriKorver niet correct - deze is 1-op-1 gelinkt met de waardes in de `enum` van `ZaakObject`

**Comment by HenriKorver** [comment]
>  niet correct - deze is 1-op-1 gelinkt met de waardes in de enum van ZaakObject

Dat begrijp ik niet. Hoe is het schema-element `status` dan gelinkt met de waardes in de `enum` van `ZaakObject`? Waar kan ik dat zien? In het zaakobject is status gewoon een string die het type van het zaakobject aanduidt.
Indien het type van het zaakobject `status` is dan zal het `object` veld van `ZaakObject` een url bevatten naar de `Status` resource (met hoofdletter):

```
Status:
      required:
      - zaak
      - statustype
      - datumStatusGezet
      type: object
      properties:
        url:
          title: Url
          description: URL-referentie naar dit object. Dit is de unieke identificatie
            en locatie van dit object.
          type: string
          format: uri
          readOnly: true
          maxLength: 1000
          minLength: 1
        uuid:
          title: Uuid
          description: Unieke resource identifier (UUID4)
          type: string
          format: uuid
          readOnly: true
        zaak:
          title: Zaak
          description: URL-referentie naar de ZAAK.
          type: string
          format: uri
        statustype:
          title: Statustype
          description: URL-referentie naar het STATUSTYPE (in de Catalogi API).
          type: string
          format: uri
          maxLength: 1000
          minLength: 1
        datumStatusGezet:
          title: Datum status gezet
          description: De datum waarop de ZAAK de status heeft verkregen.
          type: string
          format: date-time
        statustoelichting:
          title: Statustoelichting
          description: Een, voor de initiator van de zaak relevante, toelichting op
            de status van een zaak.
          type: string
          maxLength: 1000
```

De schema-definitie van 'status' (zonder hoofdletter), instantie van 'ZaakObject' is volgens mij sowieso incorrect:
```
status:
      type: object
      allOf:
      - $ref: '#/components/schemas/ZaakObject'
```
Dit is een recursieve definities want status komt ook voor in de enum van `objectType` in `ZaakObject`.
Bovendien geeft mijn Swagger-editor terecht aan dat deze definitie verder nergens gebruikt wordt in de OAS en verwijderd dient te worden.
