### ISSUE TITLE
Invalide ZRC OpenAPI  specificatie rondom rollen

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/gemma-zaken#1939]
# Bug

In de ZRC OpenAPI specificatie zitten operaties om Rollen op te vragen en om een Rol aan te maken.  Beide operaties verwijzen dan naar het schema Rol. Het schema Rol bevat het volgende:

```
Rol:
     ...
      discriminator:
        propertyName: betrokkeneType
```

In de [OpenAPI Specification ](https://swagger.io/specification/) staat het volgende bij de beschrijving van het Discriminator Object:
_The discriminator object is legal only when using one of the composite keywords oneOf, anyOf, allOf._
Deze keywords worden echter niet gebruikt in de specificatie van Rol.

Het Schema Rol moet worden voorzien van een oneOf met een verwijzing naar alle mogelijke subtypes (natuurlijk_persoon, niet_natuurlijk_persoon, vestiging, organisatorische_eenheid, medewerker)

[kies bij 'projects' voor 'Scrum ZGW Realisatie Huidige Sprint']

**Comment by michielverhoef** [comment]
@HenriKorver kun jij hier iets over zeggen?

**Comment by HenriKorver** [comment]
@andyverberne In vorige versies toen jij waarschijnlijk dit issue inbracht was er een probleem met de discriminator. Dat hebben we inmiddels opgelost met het aanmaken van expliciete mappings.

```yaml
Rol:
    ...
    discriminator:
            propertyName: betrokkeneType
            mapping:
              medewerker: '#/components/schemas/medewerker_Rol'
              natuurlijk_persoon: '#/components/schemas/natuurlijk_persoon_Rol'
              niet_natuurlijk_persoon: '#/components/schemas/niet_natuurlijk_persoon_Rol'
              organisatorische_eenheid: '#/components/schemas/organisatorische_eenheid_Rol'
              vestiging: '#/components/schemas/vestiging_Rol'
```

In ons geval wordt er gebruik gemaakt van de `allOf` constructie om de targets van deze mapping te definiëren.

```yaml
medewerker_Rol:
      allOf:
        - $ref: '#/components/schemas/Rol'
        - $ref: '#/components/schemas/betrokkene_identificatie_RolMedewerker'
```
