### ISSUE TITLE
Als API-consumer wil ik de human-readable waarde van enums tonen...

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-zaken#417]
...zodat ik zinvolle teksten/waardes kan afbeelden in plaats van 'magische codes'.

Dit refereert aan https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/pull/20 en dan specifiek mijn [suggestie](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/pull/20#issuecomment-424617891) om een read-only veld toe te voegen.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [ ] Product Owner akkoord
- [ ] Voorzien van acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] _**Userstory is ingevuld op template architectuurschets**_
- [ ] **_Userstory is voorzien van veldmapping naar RGBZ2_**
- [ ] **_Userstory past op wenselijk gebruik ZGW volgens GEMMA 2_**
- [ ] Vastgelegd Github en in geplaatst in kolom ready

**Definition of done**
- [ ] er is een OAS 3.0 specificatie
- [ ] de specificatie is gepubliceerd leesbaar
- [ ] er is een referentieimplementatie
- [ ] de DSO URI- en API-strategie worden gevolgd of afwijkingen zijn vastgelegd als ontwerp keuze
- [ ] eventueel gemaakte ontwerp keuzes zijn gedocumenteerd
- [ ] er zijn geen (nieuwe) conflicten met ontwerp keuzes in [BIP](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
Uit de algemene uitgangspunten:
- [ ] Voldoet aan RGBZ 2.0
- [ ] Voldoet aan GEMMA 2.0

**Taken**
- [ ] Opstellen welke velden bij een melding horen [_verantwoordelijke_]
- [ ] Aanleveren testdata [_verantwoordelijke_]
- [ ] Schrijven (unit) test voor referentie-implementatie [_verantwoordelijke_]
- [ ] Implementeren in referentie-implementatie [_verantwoordelijke_]
- [ ] Genereren/opstellen van OAS 3.0 [_verantwoordelijke_]
- [ ] Functionele documentatie [_verantwoordelijke_]
- [ ] Human Readable publiceren Open API Specificatie (v.3.0) [_verantwoordelijke_]

**Comment by ehotting** [comment]
Voorbeeld van een dergelijke enumeratie in onze specs?

**Comment by sergei-maertens** [comment]
@ehotting https://github.com/VNG-Realisatie/gemma-zaken/blob/master/api-specificatie/drc/openapi.yaml#L506 als voorbeeld - de werkelijke labels die hierbij horen vind je [hier](https://github.com/VNG-Realisatie/gemma-zaken-common/blob/master/zds_schema/constants.py#L9)

**Comment by terborg** [comment]
Voor de documentatie in o.a. Docusaurus hebben we hier eea voor uitgezocht, en zijn uitgekomen op `x-enumDescriptions`. Dit is binnen OpenAPI 3.0 een goed ondersteunde optie. Is geen officieel onderdeel van de OpenAPI spec, maar het wordt wel goed weergegeven.  Dit voorbeeld komt van Redocly:

````yaml
user_status:
      type: string
      enum:
        - ON
        - OFF
        - BAN
        - CAT
      title: Status indicator
      description: 'Indicates the status of the user account. This status is visible only internally to account administrators.'
      x-enumDescriptions:
        ON: User account **activated**
        OFF: User account deactivated
        BAN: User account **banned** permanently
        CAT: User is a _cat_
````

Is dit wat je ongeveer zoekt?
