### ISSUE TITLE
Toepasselijkheid discriminator attribuut uitzoeken ivm polymorphism

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-zaken#443]
# Improvement

**Definition of ready**
- [ ] Is klein genoeg (maximaal 1/5 van sprint)
- [x] Product Owner akkoord en van prioriteit voorzien
- [ ] Voorzien van Definition of Done 
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd Github en in geplaatst in kolom ready

Denk dat we dit moeten doen, zie hieronder:
"To support polymorphism, the OpenAPI Specification adds the discriminator field. When used, the discriminator will be the name of the property that decides which schema definition validates the structure of the model. As such, the discriminator field MUST be a required field."

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#models-with-polymorphism-support

```yaml
{
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "discriminator": {
          "propertyName": "petType"
        },
        "properties": {
          "name": {
            "type": "string"
          },
          "petType": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "petType"
        ]
      },
      "Cat": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
# ...
      },
      "Dog": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Pet"
          },
# ...
```
