### ISSUE TITLE
Link naar licentie in de openapi specificatie

### ISSUE THREAD

**Issue by rubenvdlinde** [VNG-Realisatie/gemma-zaken#820]
Super minor dingetje maar in de open api docs staat nu

``` YAML
license:
      name: EUPL 1.2
```

maar ietsje netter zou zijn

``` YAML
license:
      name: EUPL 1.2
      url: 'https://opensource.org/licenses/EUPL-1.2'
```

Open API ondersteund namenlijk links op licenties, en defacto moet je een licentie altijd leesbaar aanbieden anders is die zowiezo niet geldig.
